
deployement: 
  image: my-app
  tag: latest
  pullPolicy: Never

postgres:
    port: 30003
    name: postgres-3
    deployement:
      tag: latest

name: my-app-3
nameService: app-service-3

portOutside: 30002
replica: 3