version: '3'

services:
    postgres:
      container_name: etna-database
      image: postgres:latest
      environment: 
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
      volumes: 
        - postgres:/var/lib/postgresql/etna-docker
      ports: 
        - 5432:5432
volumes:
  postgres:

    
