version: '3.9'

services:
    postgres:
      container_name: etna-database
      image: postgres:latest
      environment: 
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
      volumes: 
        - postgres:/var/lib/postgresql/etna-docker
      ports: 
        - 5432:5432
    app:
      container_name: my-app
      build: 
        context: .
        dockerfile: ./Dockerfile
      volumes: 
        - app:/app
      ports:
        - '4242:80'
      depends_on: 
        - postgres
volumes:
  postgres:
    name: etna-docker
  app:

    