version: '3'

services:
    my-app:
      container_name: my-app
      build: 
        context: .
        dockerfile: ./Dockerfile
      image: my-app
      volumes: 
        - app:/app
      ports:
        - '4242:4242'
      env_file:
        - .env
volumes:
  postgres:
  app:

    
