version: '3.9'

services:
    app:
      container_name: my-app
      build: 
        context: .
        dockerfile: ./Dockerfile
      ports:
        - '4242:4242'


        # sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        # sudo chmod +x /usr/local/bin/docker-compose