apiVersion: v1
kind: Service
metadata: 
  name: "{{  .Values.nameService }}"
spec:
  selector:
    app: "{{ .Values.name }}"
  type: NodePort
  ports:
    - protocol: TCP 
      port: 4242
      targetPort: 4242
      nodePort:  {{ .Values.portOutside }}
      