apiVersion: v1
kind: Service
metadata: 
  name: "{{  .Values.nameService }}"
spec:
  selector:
    app: "{{ .Values.name }}"
  type: LoadBalancer
  ports:
    - port: 4242
      targetPort: 4242
      
      