apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.postgres.name }}"
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: "{{ .Values.postgres.name }}"
    tier: backend