apiVersion: v1
kind: ConfigMap
metadata: 
    name: postgres-config
    labels:
        group: db
data: 
    POSTGRES_DB: hefqxbvi
    POSTGRES_USER: hefqxbvi
    POSTGRES_PASSWORD: o5hme9Ksj-uO_xLGkEK6RMGTg-IcohZu